eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: athena-ribbon-client
  zipkin:
    base-url: http://localhost:8768
  sleuth:
    sampler:
      percentage: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true