eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: athena-zuul-client
  zipkin:
    base-url: http://localhost:8762
  sleuth:
    sampler:
      percentage: 1
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: athena-ribbon-client
  ignoredServices: '*'
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000