eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8761
spring:
  application:
    name: athena-zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false