eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8764
spring:
  application:
    name: briseis-eureka-client
  zipkin:
    base-url: http://localhost:8761
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672