eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: briseis-eureka-client
  zipkin:
    base-url: http://localhost:8768
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672